### ISSUE TITLE
Is an ODE solver usable within Numba within scope for this package?

### ISSUE THREAD

**Issue by jthielen** [hgrecco/numbakit-ode#23]
As a part of some recent work within MetPy (xref https://github.com/Unidata/MetPy/pull/1980), I found myself wishing I had an ODE solver that worked *within* Numba's `nopython` mode. Would such functionality be within scope for this package (or is it already present in some way)?

**Comment by hgrecco** [comment]
@jthielen Nice to see you here! 

*numbakit-ode*  is indeed intended to work in `nopython` mode (and it does!). The main limitation is mainly a limitation of numba. It is not possible now to compile and cache certain parts of the solver which means that instantiation of the solver takes a while (see #5). But the numba devs are aware and interested in resolving this.

**Comment by jthielen** [comment]
@hgrecco That sounds great! I'll be sure to experiment some more with what can be done now, and will follow the upstream issues with great interest.
