### ISSUE TITLE
Issue with speed and precision.

### ISSUE THREAD

**Issue by HiggsBoson3310** [hgrecco/numbakit-ode#25]
Hi, 
I was trying to use the package and encountered some weird behavior. I was just trying to compare with Scipy integrators, and I have found very low speeds and very jagged solutions.

I can provide the script if required, but here is the call to the integrator
`to=time.time()`
`solver = nbkode.RungeKutta45(rhs, t0=ts[0],y0=y0,params=[25.,0.5])`
`ti = time.time()`
`print("Time of initialization: %.8f s"%(ti-to))`
`ts, ys = solver.run(ts)`
`print(type(ys))`
`tf = time.time()`
`print("Numba time %.8f s, time of evaluation %.8f"%(tf-to, tf-ti))`

The timing is: 

`Scipy time 0.02010775 s`
`Time of initialization: 4.81732988 s`
`C:\..\envs\nbode\lib\site-packages\nbkode\core.py:532: NumbaExperimentalFeatureWarning: First-class function type feature is experimental`
 `if not step(t_bound, rhs, cache, *args):
<class 'numpy.ndarray'>`
`Numba time 12.74941874 s, time of evaluation 7.93208885`

and the output is very jagged
![example](https://user-images.githubusercontent.com/25889802/155750885-595955ea-188e-440d-be50-ed21a8a7f1d1.png)

Is this an issue or am I calling the integrator incorrectly? I can provide used code if necessary. I am using Windows 10, with python version 3.8.12 and my numba versions are 
`numba                     0.54.1           py38hf11a4ad_0  
numbakit-ode              0.4                      pypi_0    pypi`

**Comment by hgrecco** [comment]
Numbakit-ode is tested against scipy integrators [here](https://github.com/hgrecco/numbakit-ode/blob/main/nbkode/testsuite/test_against_scipy.py) so it should provide exactly the same result if the parameters are the same.  Can you provide information a full script? 


Ps. As a side comment, do not use `time.time()` for timing. If you do not want to use the `timeit` module, choose `time.monotoic()` or `time.perf_counter()`.

**Comment by hgrecco** [comment]
With the current main I am getting this plot:
![image](https://user-images.githubusercontent.com/278566/155855163-a5cb943d-44c7-4be1-8ded-efffb08021c2.png)

which looks the same.

**Comment by hgrecco** [comment]
Explaining the timing takes a little longer. Due to a problem with numba we cannot (yet) cache the compiled integrator and applied onto a generic function. This means that initialization takes a long time every single time.

Until this bug in numba is fixed, the performance improvement is visible only when running long simulations. But you can actually make it visible running a fixed number of steps:

```python
to=time.time()
solver = nbkode.RungeKutta45(rhs, t0=ts[0], y0=y0,params=[25.,0.5])
tsn, ysn = solver.step(n=32)
tf = time.time()
print("Numba time %.8f s"%(tf-to))
print(f"{tsn[-1]}, {len(tsn)} / {len(ts)}")

solver = nbkode.RungeKutta45(rhs, t0=ts[0], y0=y0,params=[25.,0.5])
tsn, ysn = solver.step(n=1)
to=time.time()
tsn, ysn = solver.step(n=31)
tf = time.time()
print("Numba time %.8f s"%(tf-to))
print(f"{tsn[-1]}, {len(tsn)} / {len(ts)}")
```

which prints
```python
Numba time 12.14614391 s
239.18818934278295, 32 / 5000
Numba time 0.00111103 s
239.18818934278295, 31 / 5000
```

**Comment by HiggsBoson3310** [comment]
Thanks for the explanation. I wonder if the "jaggedness" I'm seeing has to do with my installation. I'll try resinstalling and using a clean environment.

**Comment by hgrecco** [comment]
try installing directly from github to get the latest version

**Comment by HiggsBoson3310** [comment]
Update: I was not able to get the installation with windows working. I gave me this cryptic error 
```
  Resolved https://github.com/hgrecco/numbakit-ode to commit 3b2ce017f7f614d57229ac97bf5f0fe330672f52
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
```
with a bunch of lines.

I tried installing it in WSL and it worked like a charm. I can replicate the plot you obtained.
![Example](https://user-images.githubusercontent.com/25889802/155865924-8148660d-7e12-4ac9-a167-ba8e3685492c.png)

If you think the windows installation problem is important I could open another issue. 

Thank you for your help!
