### ISSUE TITLE
scipy.optimize.zeros is deprecated

### ISSUE THREAD

**Issue by duynguyenms2011** [hgrecco/numbakit-ode#26]
I installed the package from GitHub but got a following error:

AttributeError: scipy.optimize.zeros is deprecated and has no attribute _ECONVERR. Try looking in scipy.optimize instead.

**Comment by maurosilber** [comment]
Try again, it should work now.

**Comment by duynguyenms2011** [comment]
It's not working. Here are the steps that I took:
1_ clone the repo
2_ pip install . in the main directory
3_ import nbkode
4_ get an error
AttributeError: scipy.optimize.zeros is deprecated and has no attribute _ECONVERR. Try looking in scipy.optimize instead.

Please advise. Thanks!

**Comment by maurosilber** [comment]
I could reproduce that error too, but the latest commits fix them, at least
in my machine. Did you pull (and install again) the new changes?

What version of numbakit-ode do you have? When you opened the issue, it
should have installed the version numbakit-ode-0.5.dev41+g3b2ce01. Now, it
should install numbakit-ode-0.5.dev44+g0c8d49b. You can install/upgrade
directly from GitHub with:

pip install git+https://github.com/hgrecco/numbakit-ode

If you have the "dev44" version, and still get the same error message,
could you also tell me which SciPy version you have installed?

**Comment by duynguyenms2011** [comment]
I've figured it out. Thank you so much sir!

By the way, I am looking for a documentation regarding RK45 acceptable parameters, but cannot find one. Particularly, I am looking for the similar options as scipy.solve_ivp: t_eval, atol, rtol.

Would you mind giving me a list of acceptable parameters for nbkode.RungeKutta45 please?

Thank you so much!

**Comment by maurosilber** [comment]
For parameters such as atol and rtol, all variable step methods accept the
parameters shown here:
https://github.com/hgrecco/numbakit-ode/blob/0c8d49be0a06204b5a680d0db82fe086cf301258/nbkode/core.py#L664-L674

With respect to t_eval, we use a different approach, which you can read in
the docs: https://numbakit-ode.readthedocs.io/en/latest/migration.html
