### ISSUE TITLE
pip install numbakit-ode does not give the latest version

### ISSUE THREAD

**Issue by duynguyenms2011** [hgrecco/numbakit-ode#27]
I believe installing numbakit-ode does not provide the latest version. I got the following error message:

E TypeError: init() got an unexpected keyword argument 'atol'

Apparently, the version that I installed using `pip install numbakit-ode` is 0.4, and I believe the latest version is 0.5. Would you mind looking into this issue, please?
@maurosilber

**Comment by maurosilber** [comment]
Version 0.5 is now available in PyPI: https://pypi.org/project/numbakit-ode/
