### ISSUE TITLE
Issues in Tutorial Documentation

### ISSUE THREAD

**Issue by DhruvSondhi** [hgrecco/numbakit-ode#9]
Hello, 
I was trying to run some tutorial examples in a jupyter notebook but faced numerous issues while running the examples... I have seen there are small issues in the documentation for the same on https://numbakit-ode.readthedocs.io/en/latest/tutorial.html#solving-a-simple-equation ... I have solved them from my side while running the examples ... I would be very happy to fix the documentation for the same if it is possible as it may become problem for more people experimenting with the library ... Cheers :)

**Comment by hgrecco** [comment]
The API evolved since the first version. We will be releasing 0.4 in the upcoming days, maybe is better to fix the docs after that. Please check back in a week or so.

**Comment by DhruvSondhi** [comment]
Sure thing sir ... Do let me know whenever it may be possible to fix the docs ... thanks for the reply :)

**Comment by hgrecco** [comment]
The tests are fixed. Maybe you can update the docs to the current master so we can create 0.4 with the updated docs. Sounds good to you?

**Comment by DhruvSondhi** [comment]
Yes sure thing sir ... I will start it as soon as possible & create a PR for the same :+1:

**Comment by DhruvSondhi** [comment]
Sir I have created a **PR** on the same ===> #10 .... Do let me know if anything else can be done ... Would be happy to contribute :+1:
